package com.chaosmodders.chaosbeasts.client.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelDinosaur extends ModelBase
{
  //fields
    ModelRenderer Upper_Head;
    ModelRenderer Horn;
    ModelRenderer Jaw;
    ModelRenderer Neck;
    ModelRenderer Back;
    ModelRenderer Torso;
    ModelRenderer Stomache;
    ModelRenderer Upper_Left_Arm1;
    ModelRenderer Lower_Left_Arm1;
    ModelRenderer Back_Jaw;
    ModelRenderer Left_Hand;
    ModelRenderer Upper_Left_Arm2;
    ModelRenderer Lower_Left_Arm2;
    ModelRenderer Right_Hand;
    ModelRenderer Left_Upper_Leg;
    ModelRenderer Left_Upper_Thigh;
    ModelRenderer Left_Middle_Leg;
    ModelRenderer Left_Lower_Leg;
    ModelRenderer Foot1;
    ModelRenderer Right_Upper_Leg;
    ModelRenderer Right_Upper_Thigh;
    ModelRenderer Right_Middle_Leg;
    ModelRenderer Right_Lower_Leg;
    ModelRenderer Foot2;
    ModelRenderer Thick_Tail;
    ModelRenderer Thin_Tail;
    ModelRenderer Right_Claw;
    ModelRenderer Left_Claw;
  
  public ModelDinosaur()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      Upper_Head = new ModelRenderer(this, 48, 0);
      Upper_Head.addBox(0F, 0F, 0F, 3, 2, 5);
      Upper_Head.setRotationPoint(0F, 0F, 0F);
      Upper_Head.setTextureSize(64, 32);
      Upper_Head.mirror = true;
      setRotation(Upper_Head, -0.2792527F, 0F, 0F);
      Horn = new ModelRenderer(this, 40, 0);
      Horn.addBox(1.5F, 0F, -2F, 0, 1, 4);
      Horn.setRotationPoint(0F, 0F, 0F);
      Horn.setTextureSize(64, 32);
      Horn.mirror = true;
      setRotation(Horn, 2.255812F, 0F, 0F);
      Jaw = new ModelRenderer(this, 38, 5);
      Jaw.addBox(-1F, 1F, -4F, 3, 1, 2);
      Jaw.setRotationPoint(1F, 4F, 5.5F);
      Jaw.setTextureSize(64, 32);
      Jaw.mirror = true;
      setRotation(Jaw, -0.7063936F, 0F, 0F);
      Neck = new ModelRenderer(this, 34, 0);
      Neck.addBox(1F, 0F, 0F, 2, 4, 1);
      Neck.setRotationPoint(-0.5F, 2F, 0F);
      Neck.setTextureSize(64, 32);
      Neck.mirror = true;
      setRotation(Neck, -0.2230717F, 0F, 0F);
      Back = new ModelRenderer(this, 0, 0);
      Back.addBox(0F, 0F, 0F, 3, 1, 9);
      Back.setRotationPoint(0F, 7F, -9F);
      Back.setTextureSize(64, 32);
      Back.mirror = true;
      setRotation(Back, 0.2230717F, 0F, 0F);
      Torso = new ModelRenderer(this, 0, 0);
      Torso.addBox(0F, 0F, 0F, 4, 1, 9);
      Torso.setRotationPoint(-0.5F, 8F, -9F);
      Torso.setTextureSize(64, 32);
      Torso.mirror = true;
      setRotation(Torso, 0.2230717F, 0F, 0F);
      Stomache = new ModelRenderer(this, 0, 0);
      Stomache.addBox(0F, 0F, 0F, 3, 2, 9);
      Stomache.setRotationPoint(0F, 8F, -9F);
      Stomache.setTextureSize(64, 32);
      Stomache.mirror = true;
      setRotation(Stomache, 0.2230717F, 0F, 0F);
      Upper_Left_Arm1 = new ModelRenderer(this, 44, 24);
      Upper_Left_Arm1.addBox(0F, 0F, 0F, 1, 3, 1);
      Upper_Left_Arm1.setRotationPoint(-1F, 6F, -1F);
      Upper_Left_Arm1.setTextureSize(64, 32);
      Upper_Left_Arm1.mirror = true;
      setRotation(Upper_Left_Arm1, 0.2230717F, 0F, 0F);
      Lower_Left_Arm1 = new ModelRenderer(this, 44, 28);
      Lower_Left_Arm1.addBox(0F, 0F, 0F, 1, 1, 3);
      Lower_Left_Arm1.setRotationPoint(-1F, 8F, 0F);
      Lower_Left_Arm1.setTextureSize(64, 32);
      Lower_Left_Arm1.mirror = true;
      setRotation(Lower_Left_Arm1, 0F, 0F, 0F);
      Back_Jaw = new ModelRenderer(this, 56, 7);
      Back_Jaw.addBox(0F, 0F, 0F, 3, 1, 1);
      Back_Jaw.setRotationPoint(0F, 2F, 1F);
      Back_Jaw.setTextureSize(64, 32);
      Back_Jaw.mirror = true;
      setRotation(Back_Jaw, -0.3717861F, 0F, 0F);
      Left_Hand = new ModelRenderer(this, 60, 30);
      Left_Hand.addBox(0F, 0F, 0F, 1, 1, 1);
      Left_Hand.setRotationPoint(-1F, 8F, 3F);
      Left_Hand.setTextureSize(64, 32);
      Left_Hand.mirror = true;
      setRotation(Left_Hand, -0.7063936F, 0F, 0F);
      Upper_Left_Arm2 = new ModelRenderer(this, 48, 24);
      Upper_Left_Arm2.addBox(0F, 0F, 0F, 1, 3, 1);
      Upper_Left_Arm2.setRotationPoint(3F, 6F, -1F);
      Upper_Left_Arm2.setTextureSize(64, 32);
      Upper_Left_Arm2.mirror = true;
      setRotation(Upper_Left_Arm2, 0.2230717F, 0F, 0F);
      Lower_Left_Arm2 = new ModelRenderer(this, 36, 28);
      Lower_Left_Arm2.addBox(0F, 0F, 0F, 1, 1, 3);
      Lower_Left_Arm2.setRotationPoint(3F, 8F, 0F);
      Lower_Left_Arm2.setTextureSize(64, 32);
      Lower_Left_Arm2.mirror = true;
      setRotation(Lower_Left_Arm2, 0F, 0F, 0F);
      Right_Hand = new ModelRenderer(this, 60, 28);
      Right_Hand.addBox(0F, 0F, 0F, 1, 1, 1);
      Right_Hand.setRotationPoint(3F, 8F, 3F);
      Right_Hand.setTextureSize(64, 32);
      Right_Hand.mirror = true;
      setRotation(Right_Hand, -0.4089647F, 0F, 0F);
      Left_Upper_Leg = new ModelRenderer(this, 0, 26);
      Left_Upper_Leg.addBox(0F, 0F, 0F, 1, 3, 3);
      Left_Upper_Leg.setRotationPoint(3F, 8F, -9F);
      Left_Upper_Leg.setTextureSize(64, 32);
      Left_Upper_Leg.mirror = true;
      setRotation(Left_Upper_Leg, 0.6320364F, 0F, 0F);
      Left_Upper_Thigh = new ModelRenderer(this, 14, 25);
      Left_Upper_Thigh.addBox(0F, 0F, 0F, 1, 5, 2);
      Left_Upper_Thigh.setRotationPoint(4F, 8F, -8F);
      Left_Upper_Thigh.setTextureSize(64, 32);
      Left_Upper_Thigh.mirror = true;
      setRotation(Left_Upper_Thigh, 0.3717861F, 0F, 0F);
      Left_Middle_Leg = new ModelRenderer(this, 8, 20);
      Left_Middle_Leg.addBox(0F, 0F, 0F, 1, 4, 1);
      Left_Middle_Leg.setRotationPoint(4F, 11F, -6F);
      Left_Middle_Leg.setTextureSize(64, 32);
      Left_Middle_Leg.mirror = true;
      setRotation(Left_Middle_Leg, -0.5576792F, 0F, 0F);
      Left_Lower_Leg = new ModelRenderer(this, 0, 15);
      Left_Lower_Leg.addBox(0F, 0F, 0F, 1, 1, 4);
      Left_Lower_Leg.setRotationPoint(4F, 14F, -7F);
      Left_Lower_Leg.setTextureSize(64, 32);
      Left_Lower_Leg.mirror = true;
      setRotation(Left_Lower_Leg, -0.8551081F, 0F, 0F);
      Foot1 = new ModelRenderer(this, 20, 24);
      Foot1.addBox(0F, 0F, 0F, 1, 1, 3);
      Foot1.setRotationPoint(4F, 17F, -5F);
      Foot1.setTextureSize(64, 32);
      Foot1.mirror = true;
      setRotation(Foot1, 0F, 0F, 0F);
      Right_Upper_Leg = new ModelRenderer(this, 0, 20);
      Right_Upper_Leg.addBox(0F, 0F, 0F, 1, 3, 3);
      Right_Upper_Leg.setRotationPoint(-1F, 8F, -9F);
      Right_Upper_Leg.setTextureSize(64, 32);
      Right_Upper_Leg.mirror = true;
      setRotation(Right_Upper_Leg, 0.6320364F, 0F, 0F);
      Right_Upper_Thigh = new ModelRenderer(this, 8, 25);
      Right_Upper_Thigh.addBox(0F, 0F, 0F, 1, 5, 2);
      Right_Upper_Thigh.setRotationPoint(-2F, 8F, -8F);
      Right_Upper_Thigh.setTextureSize(64, 32);
      Right_Upper_Thigh.mirror = true;
      setRotation(Right_Upper_Thigh, 0.3717861F, 0F, 0F);
      Right_Middle_Leg = new ModelRenderer(this, 12, 20);
      Right_Middle_Leg.addBox(0F, 0F, 0F, 1, 4, 1);
      Right_Middle_Leg.setRotationPoint(-2F, 11F, -6F);
      Right_Middle_Leg.setTextureSize(64, 32);
      Right_Middle_Leg.mirror = true;
      setRotation(Right_Middle_Leg, -0.5576792F, 0F, 0F);
      Right_Lower_Leg = new ModelRenderer(this, 10, 15);
      Right_Lower_Leg.addBox(0F, 0F, 0F, 1, 1, 4);
      Right_Lower_Leg.setRotationPoint(-2F, 14F, -7F);
      Right_Lower_Leg.setTextureSize(64, 32);
      Right_Lower_Leg.mirror = true;
      setRotation(Right_Lower_Leg, -0.8551081F, 0F, 0F);
      Foot2 = new ModelRenderer(this, 20, 28);
      Foot2.addBox(0F, 0F, 0F, 1, 1, 3);
      Foot2.setRotationPoint(-2F, 17F, -5F);
      Foot2.setTextureSize(64, 32);
      Foot2.mirror = true;
      setRotation(Foot2, 0F, 0F, 0F);
      Thick_Tail = new ModelRenderer(this, 38, 10);
      Thick_Tail.addBox(0F, 0F, 0F, 2, 2, 5);
      Thick_Tail.setRotationPoint(0.5F, 7F, -14F);
      Thick_Tail.setTextureSize(64, 32);
      Thick_Tail.mirror = true;
      setRotation(Thick_Tail, 0F, 0F, 0F);
      Thin_Tail = new ModelRenderer(this, 52, 10);
      Thin_Tail.addBox(0F, 0F, 0F, 1, 1, 5);
      Thin_Tail.setRotationPoint(1F, 7.5F, -19F);
      Thin_Tail.setTextureSize(64, 32);
      Thin_Tail.mirror = true;
      setRotation(Thin_Tail, 0F, 0F, 0F);
      Right_Claw = new ModelRenderer(this, 52, 26);
      Right_Claw.addBox(0F, 0F, 0F, 1, 0, 3);
      Right_Claw.setRotationPoint(4F, 8F, 0F);
      Right_Claw.setTextureSize(64, 32);
      Right_Claw.mirror = true;
      setRotation(Right_Claw, 0F, -0.1115358F, 0.3717861F);
      Left_Claw = new ModelRenderer(this, 52, 29);
      Left_Claw.addBox(0F, 0F, 0F, 1, 0, 3);
      Left_Claw.setRotationPoint(-2F, 8.5F, 0F);
      Left_Claw.setTextureSize(64, 32);
      Left_Claw.mirror = true;
      setRotation(Left_Claw, 0F, 0.1858931F, -0.2974289F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Upper_Head.render(f5);
    Horn.render(f5);
    Jaw.render(f5);
    Neck.render(f5);
    Back.render(f5);
    Torso.render(f5);
    Stomache.render(f5);
    Upper_Left_Arm1.render(f5);
    Lower_Left_Arm1.render(f5);
    Back_Jaw.render(f5);
    Left_Hand.render(f5);
    Upper_Left_Arm2.render(f5);
    Lower_Left_Arm2.render(f5);
    Right_Hand.render(f5);
    Left_Upper_Leg.render(f5);
    Left_Upper_Thigh.render(f5);
    Left_Middle_Leg.render(f5);
    Left_Lower_Leg.render(f5);
    Foot1.render(f5);
    Right_Upper_Leg.render(f5);
    Right_Upper_Thigh.render(f5);
    Right_Middle_Leg.render(f5);
    Right_Lower_Leg.render(f5);
    Foot2.render(f5);
    Thick_Tail.render(f5);
    Thin_Tail.render(f5);
    Right_Claw.render(f5);
    Left_Claw.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
